services:
  db:
    image: postgres:16.4 
    restart: always
    container_name: ${DB_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - rssagg:/var/lib/postgresql/data

volumes:
  rssagg:
